spring:
  profiles:
    active: mysql
kofickey: ## 영화 진흥원 Key

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/movie_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
  quartz:
    job-store-type: jdbc
    scheduler-name: movie-schedule
  main:
    allow-bean-definition-overriding: false
  batch:
    job:
      enabled: false
