spring:
  profiles:
    active: mysql
#kofickey: c3ff4ee8a4ef39229a0b67f32520229d
kofickey: 4700c81bad7d023226fde29aa1aeed9e

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver


---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  main:
    allow-bean-definition-overriding: true
